[package]
name = "calculator"
version = "0.1.0"
authors = ["Javier Leyba"]
edition = "2018"
publish = false

[dependencies]
actix-web = "0.7"
serde = "1.0.90"
serde_derive = "1.0.90"
colored = "1.7"
rug = "1.3.0"
