[package]
name = "calculator"
version = "0.1.0"
authors = ["Javier Leyba <xleyba@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
actix-web = "0.7"
num = "0.2"
serde = "1.0.90"
serde_derive = "1.0.90"
colored = "1.7"
