[package]
name = "calculatorr"
version = "0.2.2"
authors = ["Javier Leyba"]
edition = "2018"
publish = false

[dependencies]
actix-web = "1.0.2"
serde = "1.0.92"
serde_derive = "1.0.92"
colored = "1.8"
rug = "1.4.0"
envy = "0.4.0"
log = "0.4.6"
env_logger = "0.6.1"